# Generated by Django 5.0.1 on 2024-01-17 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='agreed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='referee_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='referee_team', to='dashboard.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_one_away_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_one_home_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_two_away_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_two_home_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
