# Generated by Django 5.0.2 on 2024-02-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_teamrank_draws_teamrank_losses_teamrank_wins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamrank',
            name='team',
        ),
        migrations.DeleteModel(
            name='PlayerRank',
        ),
        migrations.DeleteModel(
            name='TeamRank',
        ),
    ]
