# Generated by Django 5.0.1 on 2024-01-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_game_agreed_alter_game_referee_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
