# Generated by Django 5.0.1 on 2024-01-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_game_away_goals_game_home_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrank',
            name='draws',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamrank',
            name='losses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamrank',
            name='wins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
